/*
 *
 * VehicleForm constants
 *
 */

const NAMESPACE = 'app/VehicleForm';

export const GET_MANUFACTURERS = `${NAMESPACE}/GET_MANUFACTURERS`;
export const GET_MANUFACTURERS_PENDING = `${NAMESPACE}/GET_MANUFACTURERS_PENDING`;
export const GET_MANUFACTURERS_FULFILLED = `${NAMESPACE}/GET_MANUFACTURERS_FULFILLED`;
export const CREATE_VEHICLE = `${NAMESPACE}/CREATE_VEHICLE`;
export const CREATE_VEHICLE_PENDING = `${NAMESPACE}/CREATE_VEHICLE_PENDING`;
export const CREATE_VEHICLE_FULFILLED = `${NAMESPACE}/CREATE_VEHICLE_FULFILLED`;
export const GET_VEHICLE = `${NAMESPACE}/GET_VEHICLE`;
export const GET_VEHICLE_PENDING = `${NAMESPACE}/GET_VEHICLE_PENDING`;
export const GET_VEHICLE_FULFILLED = `${NAMESPACE}/GET_VEHICLE_FULFILLED`;
export const UPDATE_VEHICLE = `${NAMESPACE}/UPDATE_VEHICLE`;
export const UPDATE_VEHICLE_PENDING = `${NAMESPACE}/UPDATE_VEHICLE_PENDING`;
export const UPDATE_VEHICLE_FULFILLED = `${NAMESPACE}/UPDATE_VEHICLE_FULFILLED`;
export const CLEAR_VEHICLE_STATE = `${NAMESPACE}/CREATE_VEHICLE_STATE`;

export const VEHICLE_TYPES = {
  VEHICLE_TYPE_MULTICOPTER: { id: 1, label: 'Multicopter' },
  VEHICLE_TYPE_FIXED_WING: { id: 2, label: 'Fixed Wing' },
  VEHICLE_TYPE_VTOL: { id: 3, label: 'VTOL' },
  VEHICLE_TYPE_UNKNOWN: { id: 0, label: 'Unknown' },
};

export const VEHICLE_STATES = {
  ACTIVE: { id: 'active', label: 'Active' },
  INACTIVE: { id: 'inactive', label: 'Inactive' },
};

