/*
 *
 * UserProfileForm constants
 *
 */

export const NAMESPACE = 'app/UserProfileForm';

export const GET_USER_PROFILE = `${NAMESPACE}/GET_USER_PROFILE`;
export const GET_USER_PROFILE_PENDING = `${NAMESPACE}/GET_USER_PROFILE_PENDING`;
export const GET_USER_PROFILE_FULFILLED = `${NAMESPACE}/GET_USER_PROFILE_FULFILLED`;
export const UPDATE_USER_PROFILE = `${NAMESPACE}/UPDATE_USER_PROFILE`;
export const UPDATE_USER_PROFILE_PENDING = `${NAMESPACE}/UPDATE_USER_PROFILE_PENDING`;
export const UPDATE_USER_PROFILE_FULFILLED = `${NAMESPACE}/UPDATE_USER_PROFILE_FULFILLED`;

