/*
 *
 * FlightPlanForm constants
 *
 */

const NAMESPACE = 'app/flightPlanForm';

export const CREATE_FLIGHT_PLAN = `${NAMESPACE}/CREATE_FLIGHT_PLAN`;
export const CREATE_FLIGHT_PLAN_PENDING = `${NAMESPACE}/CREATE_FLIGHT_PLAN_PENDING`;
export const CREATE_FLIGHT_PLAN_FULFILLED = `${NAMESPACE}/CREATE_FLIGHT_PLAN_FULFILLED`;
export const UPDATE_FLIGHT_PLAN = `${NAMESPACE}/UPDATE_FLIGHT_PLAN`;
export const UPDATE_FLIGHT_PLAN_PENDING = `${NAMESPACE}/UPDATE_FLIGHT_PLAN_PENDING`;
export const UPDATE_FLIGHT_PLAN_FULFILLED = `${NAMESPACE}/UPDATE_FLIGHT_PLAN_FULFILLED`;
export const GET_MISSION_TYPES = `${NAMESPACE}/GET_MISSION_TYPES`;
export const GET_MISSION_TYPES_FULFILLED = `${NAMESPACE}/GET_MISSION_TYPES_FULFILLED`;
export const GET_MISSION_TYPES_PENDING = `${NAMESPACE}/GET_MISSION_TYPES_PENDING`;
export const GET_VEHICLES = `${NAMESPACE}/GET_VEHICLES`;
export const GET_VEHICLES_FULFILLED = `${NAMESPACE}/GET_VEHICLES_FULFILLED`;
export const GET_VEHICLES_PENDING = `${NAMESPACE}/GET_VEHICLE_PENDING`;
export const GET_FLIGHT_PLAN = `${NAMESPACE}/GET_FLIGHT_PLAN`;
export const GET_FLIGHT_PLAN_FULFILLED = `${NAMESPACE}/GET_FLIGHT_PLAN_FULFILLED`;
export const GET_FLIGHT_PLAN_PENDING = `${NAMESPACE}/GET_FLIGHT_PLAN_PENDING`;
export const CLEAR_FLIGHT_PLAN_STATE = `${NAMESPACE}/CLEAR_FLIGHT_PLAN_STATE`;
export const UPLOAD_WAYPOINTS = `${NAMESPACE}/UPLOAD_WAYPOINTS`;
export const UPLOAD_WAYPOINTS_PENDING = `${NAMESPACE}/UPLOAD_WAYPOINTS_PENDING`;
export const UPLOAD_WAYPOINTS_FULFILLED = `${NAMESPACE}/UPLOAD_WAYPOINTS_FULFILLED`;
export const SET_UPLOADED_WAYPOINT = `${NAMESPACE}/SET_UPLOADED_WAYPOINT`;
export const MARK_WAYPOINTS_FOR_DELETION = `${NAMESPACE}/MARK_WAYPOINTS_FOR_DELETION`;
