# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 03:04
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20180119_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrymetadata',
            name='processor',
            field=models.IntegerField(choices=[(0, 'unknown'), (3, 'bin'), (5, 'csv'), (4, 'ddlog'), (1, 'ulog'), (2, 'tlog')], default=0, verbose_name='telemetry parser'),
        ),
    ]
