# Generated by Django 2.0.4 on 2018-04-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_mobile_16_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='mission_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='planner.MissionType'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='planner.Manufacturer'),
        ),
    ]
