# Generated by Django 2.0.4 on 2018-05-12 22:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20180507_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.CharField(default=planner.models.default_as_slug, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('state', django_fsm.FSMField(choices=[('ready', 'ready'), ('cancelreq', 'request cancellation'), ('cancelled', 'cancelled'), ('processing', 'processing'), ('success', 'success'), ('fail', 'fail'), ('submitting', 'submitting'), ('waiting', 'waiting'), ('approved', 'approved'), ('rejected', 'rejected'), ('rescinded', 'rescinded'), ('error', 'error')], default='ready', max_length=50, verbose_name='state')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('run_at', models.DateTimeField(null=True, verbose_name='run at')),
                ('submitted_at', models.DateTimeField(null=True, verbose_name='submitted at')),
                ('approved_at', models.DateTimeField(null=True, verbose_name='submitted at')),
                ('report', models.TextField(null=True, verbose_name='report path')),
                ('error', models.TextField(null=True, verbose_name='error message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='flightplan',
            name='pilot_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='pilot_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='pilot_name',
            field=models.TextField(blank=True, null=True, verbose_name='pilot name'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='pilot_phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9999999999. 10 to 15 digits allowed.', regex='^\\+\\d{10,15}$')], verbose_name='pilot mobile phone number'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='flight_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.FlightPlan'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='klass',
            field=models.TextField(default=None, verbose_name='class name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.TextField(default=None, verbose_name='short name'),
            preserve_default=False,
        ),
    ]
