# Generated by Django 2.0.4 on 2018-05-13 16:22

from django.db import migrations, models
from planner.tasks import generate_metadata, save_metadata

def add_flight_metadata(apps, schema_editor):
    FlightPlan = apps.get_model('planner', 'FlightPlan')
    fps = FlightPlan.objects.all()
    for fp in fps:
        if fp.waypoints:
            wps = fp.waypoints.waypoints.order_by('order')
            if len(wps) > 0:
                meta = generate_metadata(wps)
                save_metadata(fp.waypoints, meta)
        if fp.telemetry:
            telemetries = fp.telemetry.telemetries.order_by('time')
            if len(telemetries) > 0:
                meta = generate_metadata(telemetries)
                save_metadata(fp.telemetry, meta)

class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_assessment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrymetadata',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='location country code'),
        ),
        migrations.AddField(
            model_name='telemetrymetadata',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='distance of flight (m)'),
        ),
        migrations.AddField(
            model_name='telemetrymetadata',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='telemetrymetadata',
            name='start_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='telemetrymetadata',
            name='start_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='waypointmetadata',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='location country code'),
        ),
        migrations.AddField(
            model_name='waypointmetadata',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='distance of flight (m)'),
        ),
        migrations.AddField(
            model_name='waypointmetadata',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='waypointmetadata',
            name='start_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='waypointmetadata',
            name='start_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),

        migrations.RunPython(add_flight_metadata, migrations.RunPython.noop),
    ]
