# Generated by Django 2.0.4 on 2018-05-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_geo_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['name', 'state', 'run_at', 'approved_at'], name='planner_ass_name_a718cb_idx'),
        ),
    ]
