# Generated by Django 2.0.4 on 2018-05-24 10:20
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20180519_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrymetadata',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='location country code'),
        ),
        migrations.AlterField(
            model_name='waypointmetadata',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='location country code'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='state',
            field=django_fsm.FSMField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('invalid', 'Invalid'), ('deleted', 'Deleted')], db_index=True, default='planned', max_length=50),
        ),
    ]
